---
name: 'Generate Output'
description: 'Generates output foo without defining it in the metadata'
outputs:
  baz:
    description: "Lorem ipsum"
    value: ${{ steps.baz.outputs.baz }}
runs:
  using: "composite"
  steps:
    - id: foo
      shell: bash
      run: echo "foo=bar" >> $GITHUB_OUTPUT
    - id: baz
      shell: bash
      run: echo "baz=foo" >> $GITHUB_OUTPUT
